export const Skills = [
  {
    id: "react",
    name: "React",
    porcentaje: "50%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "javascript",
    name: "JavaScript",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "csharp",
    name: "C#",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "java",
    name: "Java",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "godot",
    name: "Godot ",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "css",
    name: "CSS3",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "html",
    name: "HTML5",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "sqlServer",
    name: "SQL SERVER",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
  {
    id: "bootstrap",
    name: "bootstrap",
    porcentaje: "80%",
    contenidos: [
      "html",
      "css",
      "lazy loading",
      "react",
      "ejemplo",
      "OtroEjemplo",
    ],
    type: "s",
  },
];
